Add context support
cabify/go-couchdb pull request #10
Opened 2018-08-14 17:46 UTC by simonsargeant

Pass context to couch HTTP requests. Anything request scoped should take context as its first parameter. This enables better control of request cancellation following context deadlines and timeouts. Also allows for handling of data stored in context which can now be read by custom transports in the http client, e.g. for tracing.

This is backwards compatible by defining new ContextAware types but deprecates the interface where context is not used.

2018-08-15 14:18 UTC, samlown commented
As I was saying to Simon via Slack and opening up here for debate, I'm not totally convinced on the `ContextAwareXXXXX` approach. Did you consider any alternatives? Strikes that it makes the API a little bit more confusing, especially when dealing with multiple instances of `ContextAwareDB` and the like. The "all or nothing" approach also makes it more more difficult to use a context in specific cases.

Have you considered for example simply adding helper methods like `func (db *DB) GetWithCtx(ctx context.Context, id string, doc interface{}, opts Options) error`?

2018-08-16 08:56 UTC, abeaumont approved these changes

2018-08-16 08:56 UTC, abeaumont commented on http.go
> +	t.addAuth(req)
Woud it make sense to have the context already linked to the request at this point?

2018-08-16 20:57 UTC, samlown requested changes
Please my previous comment.

2018-10-01 10:27 UTC, closed without merging